import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import {AppWrapper} from '@/context'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>


        <div>
        {children}
      <Footer></Footer>
        </div>
        </AppWrapper>
       
      </body>
    </html>
  );
}
